version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-services-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d